on:
  workflow_dispatch:
    inputs:
      run_branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'master'
  pull_request:
    branches:
      - master
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
      
